### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by SKYPIXEL45** [rtldg/wrsj#11]
L 12/12/2021 - 10:35:38: [SM] Exception reported: Invalid JSON in line 1, column 2089: '}' expected near end of file
L 12/12/2021 - 10:35:38: [SM] Blaming: wrsj.smx
L 12/12/2021 - 10:35:38: [SM] Call stack trace:
L 12/12/2021 - 10:35:38: [SM]   [0] HTTPResponse.Data.get
L 12/12/2021 - 10:35:38: [SM]   [1] Line 330, C:\Users\SKYPIXEL45\Desktop\CMD\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\wrsj.sp::RequestCallback

The sourcejump API key is right.

**Comment by rtldg** [comment]
sm-ripext is buggy on Windows and gives incomplete json responses. You'll have to use the SteamWorks extension and the sm-json stuff.

Change this line https://github.com/rtldg/wrsj/blob/db0223df667ddcf05a1860d5fca379c091f65946/wrsj.sp#L5
to `#define USE_RIPEXT 0`

Download the SteamWorks extension for Windows from here https://users.alliedmods.net/~kyles/builds/SteamWorks/SteamWorks-git132-windows.zip
Drop the sm-json `include` folder into your scripting folder https://github.com/clugg/sm-json/releases/tag/v3.2.1

And then recompile wrsj.sp
