### ISSUE TITLE
Steamworks+Json = Fail

### ISSUE THREAD

**Issue by sneak-it** [rtldg/wrsj#8]
When changing `#define USE_RIPEXT` to 0 and compiling, all requests fail with a generic error message:

WRSJ: failed to setup & send HTTP request

Using Steamworks ext 1.2.3 that I use successfully on all of my other servers.

**Comment by rtldg** [comment]
I think steamworks might be causing this. Here's what my server log shows me when using steamworks+json
```
RecordSteamInterfaceCreation (PID 25000): STEAMHTTP_INTERFACE_VERSION003 / UnifiedMessages
Missing interface adapter for STEAMHTTP_INTERFACE_VERSION003 UnifiedMessages
L 06/02/2021 - 07:18:20: [wrsj.smx] WRSJ: failed to setup & send HTTP request
```

**Comment by rtldg** [comment]
Nevermind to that it seems. Using a different version of steamworks gives me this which seems fine
```
RecordSteamInterfaceCreation (PID 26843): STEAMHTTP_INTERFACE_VERSION002 / HTTP
L 06/02/2021 - 07:39:53: [wrsj.smx] WRSJ: failed to setup & send HTTP request
```

**Comment by rtldg** [comment]
Should be fine now. Had to remove the `SteamWorks_SetHTTPRequestHeaderValue(request, "user-agent", USERAGENT)`  call because the SetHTTPRequestHeaderValue function [doesn't allow changing the user-agent it seems](https://partner.steamgames.com/doc/api/ISteamHTTP#SetHTTPRequestHeaderValue)
